# Generated by Django 3.2.4 on 2021-06-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='modo_preparo',
            field=models.TextField(default=''),
        ),
    ]
